CREATE TABLE wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id UUID NOT NULL,
    balance BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_wallet_player UNIQUE (player_id),
    CONSTRAINT ck_wallet_balance_non_negative CHECK (balance >= 0)
);

CREATE TABLE ledger_entries (
    id UUID PRIMARY KEY,
    wallet_id BIGINT NOT NULL,
    transaction_type VARCHAR(10) NOT NULL,
    amount BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    reason VARCHAR(255) NOT NULL,
    reference_id VARCHAR(100) NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_ledger_wallet
        FOREIGN KEY (wallet_id) REFERENCES wallets (id) ON DELETE RESTRICT,
    CONSTRAINT uk_ledger_wallet_idempotency UNIQUE (wallet_id, idempotency_key),
    CONSTRAINT ck_ledger_transaction_type
        CHECK (transaction_type IN ('CREDIT', 'DEBIT')),
    CONSTRAINT ck_ledger_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_ledger_balance_non_negative CHECK (balance_after >= 0),
    CONSTRAINT ck_ledger_reason_not_blank CHECK (CHAR_LENGTH(TRIM(reason)) > 0),
    CONSTRAINT ck_ledger_reference_not_blank CHECK (CHAR_LENGTH(TRIM(reference_id)) > 0),
    CONSTRAINT ck_ledger_idempotency_not_blank CHECK (CHAR_LENGTH(TRIM(idempotency_key)) > 0)
);

CREATE INDEX idx_ledger_wallet_history
    ON ledger_entries (wallet_id, created_at DESC, id DESC);
