package io.github.lalathomas.walletledger.wallet.application;

public enum WalletErrorCode {
    WALLET_NOT_FOUND,
    WALLET_ALREADY_EXISTS,
    TRANSACTION_NOT_FOUND,
    TRANSACTION_NOT_REFUNDABLE,
    TRANSACTION_ALREADY_REFUNDED,
    RESERVATION_NOT_FOUND,
    RESERVATION_NOT_ACTIVE,
    INSUFFICIENT_FUNDS,
    IDEMPOTENCY_CONFLICT,
    INVALID_AMOUNT,
    INVALID_REQUEST,
    BALANCE_OVERFLOW
}
